Загрузка и обработка даных из википедии.
amamonova/kontakt-game pull request #2
Opened 2019-10-15 20:01 UTC by pavlov200912

2019-10-18 10:34 UTC, roddar92 requested changes

2019-10-18 10:34 UTC, roddar92 commented on data/main.py
> +        article = re.findall('pages-articles', filename)
Чтобы регулярные выражения работали быстрее, их можно вынести из метода в начало скрипта и скомпилировать: `multistream = re.compile(r'multistream')`, а затем вызвать в самом методе: `multistream.findall(filename)`

2019-10-18 10:34 UTC, roddar92 commented on data/main.py
> +    else:
В результате этот if-else можно свернуть в конструкцию: `pattern = compiled1 if is_full else compiled2; article = pattern.findall(filename)`

2019-10-18 10:34 UTC, roddar92 commented on data/main.py
> +            data_paths.append(get_file(file, url + file))  # TODO: Add Exceptions
Здесь тоже можно спрятать if-else вовнутрь append-a :)

2019-10-18 10:34 UTC, roddar92 commented on data/main.py
> +        base_url = 'https://dumps.wikimedia.org/ruwiki/'
Здесь присвоения достаточно короткие, поэтому тоже можно воспользоваться тренарным оператором `base_url = url1 if x == 1 else url2`, флагам сразу можно присвоить `x == 1` (i.e. `download_full = x != 1`)

2019-10-18 10:34 UTC, roddar92 commented on data/wiki_code_parser.py
> +    return re.sub(clean, '', text)
`clean.sub('', text)`

2019-10-18 10:34 UTC, roddar92 commented on data/wiki_code_parser.py
> +    for i in range(0, len(l), n):
Если кода в генераторе совсем немного, то цикл можно заменить на `return (i for i in smth)` :)

2019-10-18 10:34 UTC, roddar92 commented on data/wiki_code_parser.py
> +    return re.sub(clean, '', text)
И здесь clean.sub('', text) :)

2019-10-18 10:34 UTC, roddar92 commented on data/wiki_code_parser.py
> +    if re.match("#REDIRECT", text):
В одну строку :)

2019-10-18 10:34 UTC, roddar92 commented on data/main.py
> +from bs4 import BeautifulSoup
Лучше сгруппировать все импорты в две группы: сначала импорты библиотек целиком (`import smth`), а потом импорты подбиблиотек (`from smth import that`).

А если используем методы из нашего проекта, но из других скриптов, то их следует отнести в третью замыкающую группу. :)

2019-10-18 10:34 UTC, roddar92 commented on data/data_writer.py
> +import pandas
Если импорты не используются, то, возможно, их надо на время удалить :)

2019-10-18 10:34 UTC, roddar92 commented on data/wiki_code_parser.py
> +                    example = re.sub('{{выдел|}}', ' ', example)
Тоже самое, вынести все паттерны в `compile` и затем использовать их в скрипте :)

2019-10-18 10:34 UTC, roddar92 commented on data/wiki_code_parser.py
> +    if re.match('^[ а-яА-Я]', title):
Можно преобразовать в `return pattern.match(title)`, и удалить `False` :)

2019-10-18 10:34 UTC, roddar92 commented on data/wiki_code_parser.py
> +                self._relations['synonyms'] = clean_wikilist(text, separator='[*#,]')
`[*#,]` можно спокойно вынести в константу класса :)

2019-10-18 10:34 UTC, roddar92 commented on data/wiki_code_parser.py
> +            if not self._part_of_speech and re.search('морфологические и синтаксические свойства', lower_title):
Можно упростить код, создать словарь с парами `<'antonyms', re.compile(r'антонимы')>` и так далее, и в проходе по ключам заполнить `self._relations` :)

2019-10-21 09:51 UTC, pavlov200912 commented on data/main.py
> +        article = re.findall('pages-articles', filename)
Справедливо, поправил

2019-10-21 09:51 UTC, pavlov200912 commented on data/main.py
> +    else:
Справедливо, поправил

2019-10-21 09:52 UTC, pavlov200912 commented on data/main.py
> +            data_paths.append(get_file(file, url + file))  # TODO: Add Exceptions
Кажется, что тогда будет слишком длинная строчка. К тому же, в таком длинном выражении не видно вызова функции get_file, которая стороняя и хотелось бы явно вызывать ее.

2019-10-21 09:52 UTC, pavlov200912 commented on data/main.py
> +        base_url = 'https://dumps.wikimedia.org/ruwiki/'
Справедливо, поправил

2019-10-21 09:52 UTC, pavlov200912 commented on data/wiki_code_parser.py
> +    return re.sub(clean, '', text)
Справедливо, поправил

2019-10-21 09:53 UTC, pavlov200912 commented on data/wiki_code_parser.py
> +    for i in range(0, len(l), n):
Справедливо, поправил

2019-10-21 09:53 UTC, pavlov200912 commented on data/wiki_code_parser.py
> +    return re.sub(clean, '', text)
Справедливо, поправил

2019-10-21 09:53 UTC, pavlov200912 commented on data/wiki_code_parser.py
> +    if re.match("#REDIRECT", text):
Справедливо, поправил

2019-10-21 09:53 UTC, pavlov200912 commented on data/main.py
> +from bs4 import BeautifulSoup
Справедливо, поправил

2019-10-21 09:53 UTC, pavlov200912 commented on data/data_writer.py
> +import pandas
Справедливо, поправил

2019-10-21 09:53 UTC, pavlov200912 commented on data/wiki_code_parser.py
> +                    example = re.sub('{{выдел|}}', ' ', example)
Справедливо, поправил

2019-10-21 09:53 UTC, pavlov200912 commented on data/wiki_code_parser.py
> +    if re.match('^[ а-яА-Я]', title):
Справедливо, поправил

2019-10-21 09:53 UTC, pavlov200912 commented on data/wiki_code_parser.py
> +                self._relations['synonyms'] = clean_wikilist(text, separator='[*#,]')
Справедливо, поправил

2019-10-21 09:53 UTC, pavlov200912 commented on data/wiki_code_parser.py
> +            if not self._part_of_speech and re.search('морфологические и синтаксические свойства', lower_title):
Справедливо, поправил

2019-10-21 10:40 UTC, roddar92 requested changes

2019-10-21 10:40 UTC, roddar92 commented on data/wiki_code_parser.py
> +        clean = re.compile('==[ а-яА-Я]*==')  # Remove == SubTitle ==
`clean` можно вынести в поле класса :) С `re.sub('Категория:', '', text)` сделать такие же преобразования :)

2019-10-21 10:40 UTC, roddar92 commented on data/wiki_code_parser.py
> +                    example = re_wiki_separator.sub('', example)
Пустую строку и пробел можно вынести в константы :)

2019-10-21 10:40 UTC, roddar92 commented on data/main.py
> +    base_url = 'https://dumps.wikimedia.org/ruwiki/' if x == 1 else 'https://dumps.wikimedia.org/ruwiktionary/'
Чтобы строка не была слишком длинной, можно сделать так:

`tail = 'ruwiki' if if x == 1 else 'ruwiktionary'`
`base_url = f'.../{tail}'`

2019-10-21 10:40 UTC, roddar92 commented on data/main.py
> +            data_paths.append(get_file(file, url + file))  # TODO: Add Exceptions
Точно! :)
Но еще можно написать выбор пути в отдельной строке, а потом добавлять ее в список `data_paths` :)

2019-11-08 08:01 UTC, pavlov200912 commented on data/main.py
> +    base_url = 'https://dumps.wikimedia.org/ruwiki/' if x == 1 else 'https://dumps.wikimedia.org/ruwiktionary/'
fixed

2019-11-08 08:01 UTC, pavlov200912 commented on data/wiki_code_parser.py
> +                    example = re_wiki_separator.sub('', example)
fixed

2019-11-08 08:01 UTC, pavlov200912 commented on data/wiki_code_parser.py
> +        clean = re.compile('==[ а-яА-Я]*==')  # Remove == SubTitle ==
fixed

2019-11-08 08:02 UTC, pavlov200912 commented on data/main.py
> +            data_paths.append(get_file(file, url + file))  # TODO: Add Exceptions
fixed

2019-11-08 19:24 UTC, roddar92 approved these changes

2019-11-09 14:12 UTC, amamonova approved these changes

2019-11-09 14:12 UTC, amamonova commented on data/data_writer.py
> +        self._file = open(self._path, 'w+')  # TODO w+?, exceptions!
Мне кажется, ты забыл закрыть файл после записи

2019-11-09 14:12 UTC, amamonova commented on data/main.py
> +        path = target_dir + file
я вроде слышала, что лучше конкатенировать путь через ```os.path.join()```

2019-11-09 14:12 UTC, amamonova commented on data/main.py
> +    else:
может быть тут лучше `elif x == 2`?

2019-11-09 14:12 UTC, merged